post_install() {
    mkfontscale usr/local/lib/X11/fonts/100dpi 2>/dev/null || true
    mkfontdir usr/local/lib/X11/fonts/100dpi 2>/dev/null || true
    mkfontscale usr/local/lib/X11/fonts/75dpi 2>/dev/null || true
    mkfontdir usr/local/lib/X11/fonts/75dpi 2>/dev/null || true
    mkfontscale usr/local/lib/X11/fonts/misc 2>/dev/null || true
    mkfontdir usr/local/lib/X11/fonts/misc 2>/dev/null || true
    mkfontscale usr/local/lib/X11/fonts/cyrillic 2>/dev/null || true
    mkfontdir usr/local/lib/X11/fonts/cyrillic 2>/dev/null || true
}

post_remove() {
    mkfontscale usr/local/lib/X11/fonts/100dpi 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/100dpi/fonts.scale -a "`stat -f '%25z' usr/local/lib/X11/fonts/100dpi/fonts.scale 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/100dpi/fonts.scale; fi
    mkfontdir usr/local/lib/X11/fonts/100dpi 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/100dpi/fonts.dir -a "`stat -f '%25z' usr/local/lib/X11/fonts/100dpi/fonts.dir 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/100dpi/fonts.dir; fi
    mkfontscale usr/local/lib/X11/fonts/75dpi 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/75dpi/fonts.scale -a "`stat -f '%25z' usr/local/lib/X11/fonts/75dpi/fonts.scale 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/75dpi/fonts.scale; fi
    mkfontdir usr/local/lib/X11/fonts/75dpi 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/75dpi/fonts.dir -a "`stat -f '%25z' usr/local/lib/X11/fonts/75dpi/fonts.dir 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/75dpi/fonts.dir; fi
    mkfontscale usr/local/lib/X11/fonts/misc 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/misc/fonts.scale -a "`stat -f '%25z' usr/local/lib/X11/fonts/misc/fonts.scale 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/misc/fonts.scale; fi
    mkfontdir usr/local/lib/X11/fonts/misc 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/misc/fonts.dir -a "`stat -f '%25z' usr/local/lib/X11/fonts/misc/fonts.dir 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/misc/fonts.dir; fi
    mkfontscale usr/local/lib/X11/fonts/cyrillic 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/cyrillic/fonts.scale -a "`stat -f '%25z' usr/local/lib/X11/fonts/cyrillic/fonts.scale 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/cyrillic/fonts.scale; fi
    mkfontdir usr/local/lib/X11/fonts/cyrillic 2>/dev/null || true
    if [ -e usr/local/lib/X11/fonts/cyrillic/fonts.dir -a "`stat -f '%25z' usr/local/lib/X11/fonts/cyrillic/fonts.dir 2>/dev/null`" = '2' ]; then rm usr/local/lib/X11/fonts/cyrillic/fonts.dir; fi
}
