#!/bin/sh
# arg 1:  the new package version
# arg 2:  the old package version

post_install() {
    _check_pubring
}

_check_pubring() {
    echo " >>> Run  \`pacman-key --init; pacman-key --populate archbsd\`"
    echo " >>> to import the data required by pacman for package verification."
    echo " >>> See: https://www.archlinux.org/news/having-pacman-verify-packages"
}

post_upgrade
post_install
_check_pubring
