post_install() {
    mkdir -p usr/local/share/glib-2.0/schemas
    mkdir -p usr/local/share/GConf/gsettings
    glib-compile-schemas --uninstall usr/local/share/glib-2.0/schemas
    mkdir -p usr/local/lib/gio/modules
    usr/local/bin/gio-querymodules usr/local/lib/gio/modules 2>/dev/null || /usr/bin/true
    /sbin/ldconfig -m /usr/local/lib
}

post_remove() {
    /bin/rm -f usr/local/lib/gio/modules/giomodule.cache
    /sbin/ldconfig -R
}
