# arg 1:  the new package version
post_install() {
	usr/local/bin/pango-querymodules >usr/local/etc/pango/pango.modules
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	if [ -f usr/local/etc/pango/pango.modules ]; then
		rm usr/local/etc/pango/pango.modules
	fi
	post_install $1
}

# arg 1:  the old package version
pre_remove() {
	rm usr/local/etc/pango/pango.modules
}
